const styles = {
  Alert: {
    width: "100%",
    heigth: "100%",
    position: "absolute",
    top: "0",
    right: "0",
    left: "0",
    bottom: "0",
    backgroundColor: "rgba(0,0,0,0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: "4",
  },
  AlertBox: {
    backgroundColor: "rgb(240,240,240)",
    fontFamily: "Work Sans, sans-serif",
    color: "rgb(230,0,0)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "30%",
    padding: "1rem",
    fontSize: "1.5rem",
    borderRadius: "7px",
    "& button": {
      borderRadius: "7px",
      padding: "10px",
      fontSize: "1.2rem",
      textAlign: "center",
      color: "white",
      backgroundColor: "rgba(200,0,0,0.8)",
      border: "none",
      cursor: "pointer",
      outline: "none",
      "&:hover": {
        backgroundColor: "rgba(220,0,0,1)",
      },
    },
    "& span": {
      borderRadius: "50%",
      backgroundColor: "red",
      color: "white",
      fontSize: "1.5rem",
      padding: "0.5rem 1.1rem",
    },
  },
};
export default styles;
